### ISSUE TITLE
Debug Compiled Shaders

### ISSUE THREAD

**Issue by imperiobadgo** [JeremyAnsel/JeremyAnsel.HLSL.Targets#3]
Would it be possible to provide a setting to compile a shader without optimization for better debugging (in e.g. renderDoc)?

**Comment by JeremyAnsel** [comment]
Hello,
I've added a `Debug` setting.
The default value is `false`.
When set to `true` it will directs the compiler to insert debug file/line/type/symbol information into the output code.

**Comment by imperiobadgo** [comment]
Hi, thank you very much for the quick addition!
