### ISSUE TITLE
Compiled shaders are stripped from Appx package

### ISSUE THREAD

**Issue by joelspadin** [JeremyAnsel/JeremyAnsel.HLSL.Targets#4]
To reproduce:

1. Create a new solution using the C# "Blank App, Packaged (WinUI 3 in Desktop)" template.
2. Add the JeremyAnsel.HLSL.Targets nuget package.
3. Add a .hlsl file and set its build action to "HLSL Shader".
4. Build the solution.

Inside the regular build directory, this creates an "AppX" folder for the packaged version of the app. The .cso files generated by this project are _not_ copied into this folder, so the app won't be able to load the shaders.

I haven't been able to find much documentation on this online, but I did eventually find some other projects on GitHub solving the same problem for other file types by adding an `<AppxPackagePayload>` item to their .csproj files. The following works to get the .cso file to be copied, though I couldn't tell you exactly what it's doing or why it works:

```xml
  <ItemGroup>
    <HLSLShader Include="Shaders\myshader.hlsl" />
  </ItemGroup>

  <PropertyGroup>
    <_GenerateAppxManifestDependsOn>
      ModifyAppXPackage;
      $(_GenerateAppxManifestDependsOn)
    </_GenerateAppxManifestDependsOn>
  </PropertyGroup>
  <Target Name="ModifyAppXPackage" Condition="'$(BuildingProject)' == 'true'">
    <ItemGroup>
      <Message Importance="high" Text="Modifying AppxPackagePayload" />
      <AppxPackagePayload Include="$(ProjectDir)$(OutputPath)Shaders\myshader.cso" Condition="@(AppxPackagePayload) != '' Or @(AppxPackagePayload) != '*Undefined*'">
        <TargetPath>Shaders\myshader.cso</TargetPath>
      </AppxPackagePayload>
    </ItemGroup>
  </Target>
```

It would be nice if this project could automatically tell the build system that the generated files should be included in the appx package.

The project where I ran into this is just something I hacked together to learn more about WinUI and 3D graphics, so I don't intend to publish it anywhere, but I can put together a minimal reproduction example if necessary.

**Comment by JeremyAnsel** [comment]
Hello,
I've updated the library.

I've included the above target.

Can you test if it works for you?

**Comment by joelspadin** [comment]
That looks like it's working. Thanks!
